version: '1.0'
name: master
displayName: master
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - master
stages:
  - name: stage-13208622
    displayName: 编译
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 16.14.2
        commands:
          - '# 设置NPM源，提升安装速度'
          - npm config set registry https://registry.npmmirror.com
          - ''
          - '# 执行编译命令'
          - npm install && npm run build
        caches: []
        notify:
          - certificate: 7b2dc8f0-9a3e-013b-6e47-16f9fc8fe7ed
            events:
              - fail
            content:
              - repository
              - pipeline
              - stage
              - task
              - operator
              - branch
              - detail
            type: dingtalk
        strategy:
          retry: '0'
